// Generated by gencpp from file edrom_tutorial/AddTwoInts.msg
// DO NOT EDIT!


#ifndef EDROM_TUTORIAL_MESSAGE_ADDTWOINTS_H
#define EDROM_TUTORIAL_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <edrom_tutorial/AddTwoIntsRequest.h>
#include <edrom_tutorial/AddTwoIntsResponse.h>


namespace edrom_tutorial
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace edrom_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::edrom_tutorial::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::edrom_tutorial::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::edrom_tutorial::AddTwoInts > {
  static const char* value()
  {
    return "edrom_tutorial/AddTwoInts";
  }

  static const char* value(const ::edrom_tutorial::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::edrom_tutorial::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::edrom_tutorial::AddTwoInts >
template<>
struct MD5Sum< ::edrom_tutorial::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::edrom_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::edrom_tutorial::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::edrom_tutorial::AddTwoIntsRequest> should match
// service_traits::DataType< ::edrom_tutorial::AddTwoInts >
template<>
struct DataType< ::edrom_tutorial::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::edrom_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::edrom_tutorial::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::edrom_tutorial::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::edrom_tutorial::AddTwoInts >
template<>
struct MD5Sum< ::edrom_tutorial::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::edrom_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::edrom_tutorial::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::edrom_tutorial::AddTwoIntsResponse> should match
// service_traits::DataType< ::edrom_tutorial::AddTwoInts >
template<>
struct DataType< ::edrom_tutorial::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::edrom_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::edrom_tutorial::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EDROM_TUTORIAL_MESSAGE_ADDTWOINTS_H
