// Generated by gencpp from file edrom_tutorial/edrom_message.msg
// DO NOT EDIT!


#ifndef EDROM_TUTORIAL_MESSAGE_EDROM_MESSAGE_H
#define EDROM_TUTORIAL_MESSAGE_EDROM_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edrom_tutorial
{
template <class ContainerAllocator>
struct edrom_message_
{
  typedef edrom_message_<ContainerAllocator> Type;

  edrom_message_()
    : str()  {
    }
  edrom_message_(const ContainerAllocator& _alloc)
    : str(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _str_type;
  _str_type str;





  typedef boost::shared_ptr< ::edrom_tutorial::edrom_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edrom_tutorial::edrom_message_<ContainerAllocator> const> ConstPtr;

}; // struct edrom_message_

typedef ::edrom_tutorial::edrom_message_<std::allocator<void> > edrom_message;

typedef boost::shared_ptr< ::edrom_tutorial::edrom_message > edrom_messagePtr;
typedef boost::shared_ptr< ::edrom_tutorial::edrom_message const> edrom_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edrom_tutorial::edrom_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edrom_tutorial::edrom_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edrom_tutorial::edrom_message_<ContainerAllocator1> & lhs, const ::edrom_tutorial::edrom_message_<ContainerAllocator2> & rhs)
{
  return lhs.str == rhs.str;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edrom_tutorial::edrom_message_<ContainerAllocator1> & lhs, const ::edrom_tutorial::edrom_message_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edrom_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edrom_tutorial::edrom_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edrom_tutorial::edrom_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edrom_tutorial::edrom_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edrom_tutorial::edrom_message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edrom_tutorial::edrom_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edrom_tutorial::edrom_message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edrom_tutorial::edrom_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "994972b6e03928b2476860ce6c4c8e17";
  }

  static const char* value(const ::edrom_tutorial::edrom_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x994972b6e03928b2ULL;
  static const uint64_t static_value2 = 0x476860ce6c4c8e17ULL;
};

template<class ContainerAllocator>
struct DataType< ::edrom_tutorial::edrom_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edrom_tutorial/edrom_message";
  }

  static const char* value(const ::edrom_tutorial::edrom_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edrom_tutorial::edrom_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string str\n"
;
  }

  static const char* value(const ::edrom_tutorial::edrom_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edrom_tutorial::edrom_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct edrom_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edrom_tutorial::edrom_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edrom_tutorial::edrom_message_<ContainerAllocator>& v)
  {
    s << indent << "str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDROM_TUTORIAL_MESSAGE_EDROM_MESSAGE_H
